#!/usr/bin/env python3
"""Derive a free-Apple-ID XcodeGen spec from the full one.

A personal (free) Apple developer team cannot provision the App Groups
capability, and signing fails outright rather than degrading — so every target
that declares it is unbuildable on a free account. This script produces a
variant spec with those declarations, and the two extensions that genuinely
need the shared container, removed.

What survives, and why it is worth having:

  VocalIOS      main-app dictation, the Action Button intent, history,
                dictionary, profiles. The app already treats an unreachable
                container as "no bridge" (`BridgeStore.appGroup()` returns nil
                and `isBridgeAvailable` goes false), so no code changes are
                needed — the Keyboard settings screen simply says so.
  VocalWidgets  the Dynamic Island / Lock Screen recording indicator. It reads
                its state from ActivityKit, never from the App Group, so it
                needs no entitlement at all.
  VocalMac      untouched.

What is dropped: VocalKeyboard and VocalShareExt. Both exist only to move data
across the App Group boundary, so without it there is nothing for them to do.

Deliberately stdlib-only and line-based: `pyyaml` is not present on a stock
macOS python3, and this has to run on the owner's Mac with no setup. The
transform is driven by indentation, which is sound here because the input is
one file in this repo that CI regenerates and builds on every change.
"""

from __future__ import annotations

import sys

# Targets that cannot work without a shared container.
DROPPED_TARGETS = ("VocalKeyboard", "VocalShareExt")

TARGET_INDENT = "  "
KEY_INDENT = "    "


def block_end(lines: list[str], start: int, indent: str) -> int:
    """Index just past the block opened at `start` by a key at `indent`.

    A block runs until the next non-blank line indented no deeper than its
    opening key.
    """
    for index in range(start + 1, len(lines)):
        line = lines[index]
        if not line.strip():
            continue
        if not line.startswith(indent + " ") and not line.startswith(indent + "\t"):
            if len(line) - len(line.lstrip(" ")) <= len(indent):
                return index
    return len(lines)


def preceding_comment_start(lines: list[str], index: int) -> int:
    """Walk back over the comment lines that introduce the block at `index`.

    A dropped target takes its own explanatory comment with it; leaving the
    comment behind would describe a target that is not there.
    """
    start = index
    while start > 0:
        previous = lines[start - 1].strip()
        if previous.startswith("#"):
            start -= 1
        else:
            break
    return start


def transform(text: str) -> str:
    lines = text.splitlines()
    drop = [False] * len(lines)

    index = 0
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()

        # A whole target block, plus the comment that introduces it.
        if line.startswith(TARGET_INDENT) and not line.startswith(TARGET_INDENT + " "):
            name = stripped.rstrip(":")
            if name in DROPPED_TARGETS:
                end = block_end(lines, index, TARGET_INDENT)
                for mark in range(preceding_comment_start(lines, index), end):
                    drop[mark] = True
                index = end
                continue

        # Any App Group entitlement declaration, on every target that has one.
        if line == KEY_INDENT + "entitlements:":
            end = block_end(lines, index, KEY_INDENT)
            for mark in range(index, end):
                drop[mark] = True
            index = end
            continue

        # The embed dependencies pointing at the dropped extensions.
        if stripped.startswith("- target: "):
            if stripped[len("- target: ") :] in DROPPED_TARGETS:
                end = block_end(lines, index, " " * (len(line) - len(line.lstrip(" "))))
                for mark in range(index, end):
                    drop[mark] = True
                index = end
                continue

        index += 1

    kept = [line for line, dropped in zip(lines, drop) if not dropped]
    output = "\n".join(kept)

    # A distinct project name so the free build sits beside the full one
    # instead of silently replacing it.
    output = output.replace("\nname: Vocal\n", "\nname: VocalFree\n", 1)

    header = (
        "# GENERATED by scripts/free-account-spec.py — do not edit.\n"
        "# Source of truth is project.yml; regenerate with `make generate-free`.\n"
        "#\n"
        "# Free-Apple-ID variant: no App Groups (a personal team cannot provision\n"
        "# them), so the keyboard and share extensions are absent. Main-app\n"
        "# dictation and the Dynamic Island are unaffected.\n"
    )
    return header + output + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("usage: free-account-spec.py <in-spec> <out-spec>", file=sys.stderr)
        return 2

    source, destination = argv[1], argv[2]
    with open(source, encoding="utf-8") as handle:
        text = handle.read()

    result = transform(text)

    # Fail loudly rather than emit a spec that would still fail to sign.
    for target in DROPPED_TARGETS:
        if f"\n  {target}:" in result:
            print(f"error: {target} survived the transform", file=sys.stderr)
            return 1
    if "application-groups" in result:
        print("error: an App Group entitlement survived the transform", file=sys.stderr)
        return 1
    if "\n  VocalIOS:" not in result or "\n  VocalWidgets:" not in result:
        print("error: the transform removed a target it should have kept", file=sys.stderr)
        return 1

    with open(destination, "w", encoding="utf-8") as handle:
        handle.write(result)
    print(f"wrote {destination} (dropped: {', '.join(DROPPED_TARGETS)}, no App Groups)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
